### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nicolasmol** [sebastianxyzsss/tardigrade#1]
Linux mint 20.1
Just installed it.
Ran _tg_ with default set of commands
Took  "ls -la":

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x6498f1]
> 
> goroutine 1 [running]:
> github.com/sebastianxyzsss/tardigrade/selecter.finalElementApply(0xc0000c57d8?, 0xc0001559d0)
>         /home/sebastian/develop/sebxyzsss/tardigrade/selecter/selecter.go:74 +0x151
> github.com/sebastianxyzsss/tardigrade/selecter.Chooser(0xc0001558f0, 0xc000155800?)
>         /home/sebastian/develop/sebxyzsss/tardigrade/selecter/selecter.go:132 +0x2cc
> main.runTardigrade({0x0, 0x0, 0x0})
>         /home/sebastian/develop/sebxyzsss/tardigrade/main.go:157 +0x354
> main.main()
>         /home/sebastian/develop/sebxyzsss/tardigrade/main.go:40 +0xa5
![image](https://github.com/sebastianxyzsss/tardigrade/assets/61077647/bf7b0f54-1c06-4651-a90a-9beab4ba925d)

**Comment by sebastianxyzsss** [comment]
Hi, Thanks for installing. As of the 0.0.2 version, you would need to create a new user home file, first type the command tg -n, then it should work typing tg after that. I tested on debian and I got the same error. I understand it is not very obvious to do tg -n at first. I am working for tardigrade to initialize itself for the future versions, so there will not be a need to create with a -n flag.
